/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'fcb' at '10/25/18 11:02 AM' with Gradle 2.10
 *
 * @author fcb, @date 10/25/18 11:02 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
